version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm i
      - persist_to_workspace:
          root: ~/project
          paths:
            - package.json
            - package-lock.json
            - node_modules/*
            - src/*
  lint:
    docker:
      - image: circleci/node:8
    steps:
      - run: echo lint
  test:
    docker:
      - image: circleci/node:8
    steps:
      - attach_workspace:
          at: ~/project
      - run: npm test
  build:
    docker:
      - image: circleci/node:8
    steps:
      - run: echo build
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - run: echo deploy   

workflows:
  version: 2
  build-test:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - test:
          requires:
            - checkout_code
      - build:
          requires:
            - checkout_code
      - deploy:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
