version: 2

jobs:
  checkout_code:
    docker:
      - image: circleci/node:8
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
workflows:
  version: 2
  build-test:
    jobs:
      - checkout_code
